### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by rafecolton**
/cc @jszwedko

### CODE REVIEW

**Comment by jszwedko** [comment]
So it turns out there is a `lookup` for etcd in ansible: https://github.com/ansible/ansible/pull/4664

**Comment by rafecolton** [comment]
@jszwedko indeed it does - I'll update this pull request to only include the set and delete operations

**Comment by rafecolton** [comment]
@jszwedko bump

**Comment by jszwedko** [comment]
Could you add some docz, e.g. https://github.com/ansible/ansible/blob/devel/examples/DOCUMENTATION.yml ?

Otherwise :shipit:

**Comment by rafecolton** [comment]
@jszwedko bump - added docs and support for check mode

**Comment by jszwedko** [comment]
I'm getting:

```
failed: [192.168.113.127] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/j.szwedko/.ansible/tmp/ansible-tmp-1412002596.46-41666389224869/etcd", line 1544, in <module>
    main()
  File "/Users/j.szwedko/.ansible/tmp/ansible-tmp-1412002596.46-41666389224869/etcd", line 1473, in main
    client = etcd.Client(**kwargs)
AttributeError: 'module' object has no attribute 'Client'
```

**Comment by jszwedko** [comment]
I also needed to install `etcd` via `pip` rather than `python-etcd` (this module complained about the import if I just installed the latter).

**Comment by jszwedko** [comment]
But I may be doing something wrong!

**Comment by rafecolton** [comment]
@jszwedko can you elaborate on the module's complaints?  That's not something I'm seeing.

`python-etcd` uses `etcd.Client()` while `etcd` uses and `etcd.client.Client()`, so that would explain the panic.

FWIW, it looks like both packages are [reasonably complete and official](https://github.com/coreos/etcd/blob/master/Documentation/clients-matrix.md).

**Comment by jszwedko** [comment]
Yep, works now. Not sure what I was doing wrong. One last nitpicks :smile: :

Can the examples be updated to use `=` instead of `:`? Seems more conventional use of ansible modules though both syntaxes work.

**Comment by jszwedko** [comment]
Otherwise :shipit: !

**Comment by rafecolton** [comment]
@jszwedko sure thing - bump!

**Comment by jszwedko** [comment]
Nice, thank you!

**Pull request merged**
